[package]
name = "sey"
version = "0.1.0"
authors = ["Ian Tabolt <ian@tabo.lt>"]
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
crossterm = "0.28"
ignore = "0.4"
ratatui = { version = "0.29", default-features = false, features = ["crossterm"] }
regex = "1"
termcolor = "1"
